const words = [
  { word: "cryptocurrency", hint: "Digital or virtual currencies that use cryptography for security." },
  { word: "bureaucracy", hint: "A system of government or management characterized by excessive red tape and inefficiency." },
  { word: "phenomenon", hint: "A remarkable or exceptional person, thing, or event." },
  { word: "hypothesis", hint: "A proposed explanation for a phenomenon based on available evidence." },
  { word: "surreptitious", hint: "Kept secret or done in a way that avoids notice." },
  { word: "quixotic", hint: "Exceedingly idealistic; unrealistic and impractical." },
  { word: "ubiquitous", hint: "Present, appearing, or found everywhere." },
  { word: "juxtaposition", hint: "The fact of two things being seen or placed close together with contrasting effect." },
  { word: "serendipity", hint: "The occurrence of events by chance in a happy or beneficial way." },
  { word: "paradox", hint: "A statement that contradicts itself but may still be true." },
  { word: "sycophant", hint: "A person who acts obsequiously towards someone important to gain advantage." },
  { word: "equivocate", hint: "Use ambiguous language to conceal the truth or avoid committing oneself." },
  { word: "quagmire", hint: "A soft boggy area of land that gives way underfoot; a complex or hazardous situation." },
  { word: "iconoclast", hint: "A person who attacks or criticizes cherished beliefs or institutions." },
  { word: "paradigm", hint: "A typical example or pattern of something; a model." },
  { word: "anomaly", hint: "Something that deviates from what is standard, normal, or expected." },
  { word: "mnemonic", hint: "A device such as a pattern of letters, ideas, or associations that assists in remembering something." },
  { word: "quintessential", hint: "Representing the most perfect or typical example of a quality or class." },
  { word: "facetious", hint: "Treating serious issues with deliberately inappropriate humor; flippant." },
  { word: "ephemeral", hint: "Lasting for a very short time." },
  { word: "ubiquity", hint: "The state of being everywhere or in many places simultaneously." },
  { word: "perpendicular", hint: "At an angle of 90 degrees to a given line, plane, or surface." },
  { word: "quintessence", hint: "The most perfect embodiment of something." },
  { word: "soliloquy", hint: "An act of speaking one's thoughts aloud when alone or regardless of any hearers, especially by a character in a play." },
  { word: "procrastinate", hint: "Delay or postpone action; put off doing something." },
  { word: "apple", hint: "A popular fruit that is often red or green." },
  { word: "banana", hint: "A long, curved fruit that is yellow when ripe." },
  { word: "elephant", hint: "A large mammal with a long trunk and tusks." },
  { word: "computer", hint: "A device used for processing data and running programs." },
  { word: "ocean", hint: "A vast body of saltwater covering most of the Earth's surface." },
  { word: "mountain", hint: "A large natural elevation of the Earth's surface." },
  { word: "guitar", hint: "A musical instrument with strings that is played by strumming or plucking." },
  { word: "pizza", hint: "A popular Italian dish consisting of a round, flat base topped with cheese and other ingredients." },
  { word: "sunflower", hint: "A tall plant with large, yellow flowers that turn towards the sun." },
  { word: "bicycle", hint: "A two-wheeled vehicle propelled by pedals." },
  { word: "umbrella", hint: "A device used to protect against rain or sunlight, typically consisting of a collapsible canopy attached to a metal frame." },
  { word: "library", hint: "A place where books, documents, and other materials are stored and made available for borrowing or reading." },
  { word: "moon", hint: "The natural satellite of the Earth." },
  { word: "robot", hint: "A machine capable of carrying out complex actions automatically, often resembling a human or animal." },
  { word: "chocolate", hint: "A sweet, brown food made from roasted and ground cacao seeds." },
  { word: "sunglasses", hint: "Eyewear designed to protect the eyes from sunlight or glare." },
  { word: "keyboard", hint: "A set of keys or buttons used to input data into a computer or other device." },
  { word: "penguin", hint: "A flightless bird native to the Southern Hemisphere." },
  { word: "beach", hint: "A sandy or pebbly shore by the ocean or a lake." },
  { word: "camera", hint: "A device used to capture and record images or videos." },
  { word: "soccer", hint: "A team sport played with a spherical ball between two teams of eleven players." },
  { word: "dragon", hint: "A mythical creature resembling a giant reptile, often depicted with wings and breathing fire." },
  { word: "volcano", hint: "A mountain or hill with a crater or vent through which lava, rock fragments, ash, and gases erupt." },
  { word: "garden", hint: "An area of land used for growing flowers, fruits, vegetables, or herbs." }
];